
import "./globals.css";
import SessionProviderWrapper from "@/providers/SessionProviderWrapper.js"


export const metadata = {
  title: "MentoMap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
